server:
  port: 8082
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    schema: classpath:/scripts/schema.sql
    data: classpath:/scripts/data.sql

# Oauth2 resource server configuration
security:
  oauth2:
    resource:
      id: USER_CLIENT_RESOURCE
      token-info-uri: http://localhost:8080/oauth/check_token
    client:
      client-id: 8765dbfe-48a7-4d2b-8cf4-cdf10aae46e4
      client-secret: 708f5e55-eb4d-4b4c-85af-381239d47213
      grantType: client_credentials
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize

logging:
  level:
    org:
      springframework:
        security: DEBUG

