drop table if exists dateofbirth CASCADE;
drop table if exists location CASCADE;
drop table if exists login CASCADE;
drop table if exists profile CASCADE;
create table dateofbirth
(id integer generated by default as identity,
age integer,
dob timestamp, primary key (id)
);

create table location
(id integer generated by default as identity,
city varchar(255),
postcode integer,
state varchar(255),
street varchar(255), primary key (id));

create table login
(id integer generated by default as identity,
password varchar(255),
username varchar(255),
uuid varchar(255), primary key (id));

create table profile
(id integer generated by default as identity,
cell varchar(255), email varchar(255),
first_name varchar(255),
gender varchar(10),
last_name varchar(255),
middle_name varchar(255),
phone varchar(255),
date_of_birth_id integer,
location_id integer,
login_id integer, primary key (id)
);

alter table profile add constraint FK7oar0m2ut4o3849ie9u8xtfcn foreign key (date_of_birth_id) references dateofbirth;
alter table profile add constraint FKla9kopl4kgeg1jr3iq5t9ii0t foreign key (location_id) references location;
alter table profile add constraint FKjey7dvhp3w05oebq4hdvlhngi foreign key (login_id) references login;